name: Order
doc: Single order
namespace: messaging
type: record
fields:


- name: meta
  doc: 'Additional info. Maximum double nested dictionary with string keys'
  type:
    type: map
    values:
      - "null"
      - "boolean"
      - "int"
      - "long"
      - "float"
      - "double"
      - "bytes"
      - "string"
