name: union_schema
doc: Metadata of the execution signal specific to the Active Watchdog strategy.
namespace: messaging
type: record
fields:

  - name: imbalance
    description: Imbalance of the broker at the time of the detected change
    type: "string"
  
  - name: error
    description: Error of the linear regression
    type: "string"

  - name: price
    description: Last detected price
    type: "string"
