name: BBGStockInfo
doc: BBG tick data - stock info
namespace: messaging
type: record
fields:

- name: timeseries_identifier
  doc: 'Seconds since 2018-01-01 when data download process was launched'
  type: int

- name: time
  doc: 'Time of state change [UNIX timestamp]'
  type: double

- name: security
  doc: 'BBG security id'
  type: string

- name: index
  doc: 'BBG tick data chronological index'
  type: int

- name: state
  doc: 'Market state changes'
  type: ['null', string]
